### ISSUE TITLE
Improve pandas use for DataFrame aggregated updates by author 

### ISSUE THREAD

**Issue by axelofwar** [axelofwar/chatGPT-help-bot#5]
## GOAL
The goal of this issue is to improve the handling of DataFrame members. Currently, We are are tracking the IDs of the following tweet interactions: 
> - author 
> - included
> - engager

We would like to use these in order to aggregate engagement metrics for each account as appropriately, and then update the data frame objects with those aggregated values. 

## TODO
The data frames are created and are being populated on each call successfully already. I am trying to use the locate ```csv.loc``` function in order to find the index in the database and update its value member, but for some reason this doesn't appear to be working (or it is and I am overwriting the print somewhere else).

I would like to improve that location handling - or other csv updating method in order to aggregate and update the fields instead of creating a new line in the outputs/df.csv output each time - including replications of authors that already exist in in the index. Potentially will need to index by number and compare number instead of strings. 

## Acceptance Criteria
- [ ] author indexed and located if existent in ```outputs/df.csv```
- [ ] ```outputs/df.csv``` updated and no duplicate members contained
- [ ] engagement metrics aggregated/updated instead of replaced in ```outputs/df.csv```

**Comment by axelofwar** [comment]
I've updated the code to better store the csv members, as well as added the capability to access specific members of the .csv. I may need to change the way that I am checking if the user is already in the database from using ```outputs_df.index``` to a more for-loop iterator type approach using ```author = df['Author']``` and an index based iterator - less efficient but higher chance of success with shorter MVP turnaround. 

> I also began experimenting with using .json instead of .csv for: 
> - potentially easier integration with API responses
> - avoidance of comma repeats to output when using .csv
> - better index handling to access author members
>
> Feel free to pick up on that and use .json for the database type interactions instead if it will make solving the issue easier! I have a branch [open](https://github.com/axelofwar/chatGPT-help-bot/tree/axelofwar-improve-pandas-json-csv) to track progress on better database integration separate from the api and data aggregation functionality with likes, tweets, and retweets to a specified account.
